# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py313"

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
]

[lint.per-file-ignores]
"tests/*.py" = [
    "S101", # assert statements are allowed in tests
    "PLR2004", # magic values are common in tests
    "FBT001", # boolean positional arguments are common in test helpers
    "FBT002", # boolean default positional arguments are common in test helpers
    "FBT003", # boolean positional values are common in test calls
    "PLR0913", # too many arguments are common in comprehensive test functions
    "SLF001", # private member access is common in tests
    "F841", # unused variables are common in tests
    "C901", # complex structures are common in comprehensive E2E tests
    "PLR0912", # too many branches are common in comprehensive E2E tests
    "PLR0915", # too many statements are common in comprehensive E2E tests
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25
