# https://www.home-assistant.io/integrations/default_config/
default_config:
# automation:
# backup:
# bluetooth:
# config:
# conversation:
# counter:
# dhcp:
# energy:
# frontend:
# hardware:
# history:
# homeassistant_alerts:
# cloud:
# image_upload:
# input_button:
# input_datetime:
# input_select:
# input_text:
# logbook:
# media_source:
# mobile_app:
# my:
# person:
# schedule:
# scene:
# script:
# ssdp:
# stream:
# sun:
# system_health:
# tag:
# timer:
# usb:
# webhook:
# zeroconf:
# zone:

api:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.room_ventilation_advisor: debug


## dummy configuration for room ventilation advisor
# configuration.yaml

